# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "depix"
  s.version = "3.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Julik Tarkhanov"]
  s.date = "2011-11-29"
  s.description = "Allows you to read and edit DPX file headers parsed into Ruby objects"
  s.email = "me@julik.nl"
  s.executables = ["depix_describe", "depix_fix_headers"]
  s.extra_rdoc_files = [
    "DPX_HEADER_STRUCTURE.rdoc",
    "README.rdoc"
  ]
  s.files = [
    ".gemtest",
    ".travis.yml",
    "DPX_HEADER_STRUCTURE.rdoc",
    "Gemfile",
    "History.txt",
    "README.rdoc",
    "Rakefile",
    "bin/depix_describe",
    "bin/depix_fix_headers",
    "depix.gemspec",
    "lib/depix.rb",
    "lib/depix/binary/fields.rb",
    "lib/depix/binary/rdoc_generator.rb",
    "lib/depix/binary/structure.rb",
    "lib/depix/compact_structs.rb",
    "lib/depix/describe.rb",
    "lib/depix/editor.rb",
    "lib/depix/enums.rb",
    "lib/depix/reader.rb",
    "lib/depix/structs.rb",
    "lib/depix/synthetics.rb",
    "test/samples/026_FROM_HERO_TAPE_5-3-1_MOV.0029.dpx",
    "test/samples/E012_P001_L000002_lin.0001.dpx",
    "test/samples/E012_P001_L000002_lin.0002.dpx",
    "test/samples/E012_P001_L000002_log.0001.dpx",
    "test/samples/E012_P001_L000002_log.0002.dpx",
    "test/samples/from_nuke_no_TC_meta.dpx",
    "test/samples/gluetools_file_header.dpx",
    "test/samples/little_endian.dpx",
    "test/samples/northlight_tc_mode_mismatch.dpx",
    "test/samples/scratch.dpx",
    "test/test_binary.rb",
    "test/test_depix.rb",
    "test/test_describe.rb",
    "test/test_fix_headers.rb"
  ]
  s.homepage = "http://guerilla-di.org/depix"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "Read and write DPX file headers"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<timecode>, ["~> 1.0"])
      s.add_runtime_dependency(%q<progressbar>, ["~> 0.9"])
      s.add_runtime_dependency(%q<sequencer>, ["~> 1.0"])
      s.add_runtime_dependency(%q<term-ansicolor>, [">= 0"])
      s.add_runtime_dependency(%q<update_hints>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<cli_test>, ["~> 1.0"])
    else
      s.add_dependency(%q<timecode>, ["~> 1.0"])
      s.add_dependency(%q<progressbar>, ["~> 0.9"])
      s.add_dependency(%q<sequencer>, ["~> 1.0"])
      s.add_dependency(%q<term-ansicolor>, [">= 0"])
      s.add_dependency(%q<update_hints>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<cli_test>, ["~> 1.0"])
    end
  else
    s.add_dependency(%q<timecode>, ["~> 1.0"])
    s.add_dependency(%q<progressbar>, ["~> 0.9"])
    s.add_dependency(%q<sequencer>, ["~> 1.0"])
    s.add_dependency(%q<term-ansicolor>, [">= 0"])
    s.add_dependency(%q<update_hints>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<cli_test>, ["~> 1.0"])
  end
end

